### ISSUE TITLE
PVs are provisioned for StorageClasses with unavailable zones

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#1005]
There is a slight behavioral change between in-tree and migrated GCP PD volume plugin:
* In-tree volume plugin refuses to provision a volume in a GCP zone that does not have a node instance
* The CSI driver provisions a new volume in this case. It does not check (cannot check?) if the requested zone has a node in it. The provisioned PV is then unusable in the cluster.

Steps to reproduce:

1. SC explicitly wants `europe-west1-d`:
    <details>
    
    ```
    allowVolumeExpansion: true
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      annotations:
        storageclass.kubernetes.io/is-default-class: "false"
      name: sc-4fap4
    parameters:
      replication-type: none
      type: pd-standard
      zone: europe-west1-d
    provisioner: kubernetes.io/gce-pd
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    ```
    
    </details>

2. All nodes are in `us-east1-{b-d}`:
    <details>
    
    ```
    $ kubectl get node -o yaml | grep topology.kubernetes.io/zone
          topology.kubernetes.io/zone: us-east1-b
          topology.kubernetes.io/zone: us-east1-c
          topology.kubernetes.io/zone: us-east1-d
          topology.kubernetes.io/zone: us-east1-b
          topology.kubernetes.io/zone: us-east1-c
          topology.kubernetes.io/zone: us-east1-d
    ```
    
    </details>

3. User creates a PVC requesting the SC from step 1.
    <details>
    
    ```
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: mypvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: sc-4fap4
      volumeMode: Filesystem
    ```
    
    </details>

With in-tree volume plugin, I get an error event:

`
Warning  ProvisioningFailed     Failed to provision volume with StorageClass "sc-4fap4": kubernetes does not have a node in zone "europe-west1-d"
`

With CSI migration enabled, a PV is provisioned in europe-west1-d and the PV cannot be attached to any node in the cluster.

It would be probably hard to fix it correctly, the CSI driver does not know what nodes are in the cluster. IMO it would be enough just to document it somehow.

https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/1005#tasklist-block-ea1281d9-ceba-45ae-bf0a-b11f82676598
