### ISSUE TITLE
Feature Request: Transition the Node component to become a HostProcess Pod

### ISSUE THREAD

**Issue by mauriciopoppe** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#1057]
A HostProcess pod can execute privileged storage operations directly, the idea to use it in PD CSI Driver is:

- Refactor CSI Proxy to become a library.
- Replace the client code in PD CSI Driver that uses the gRPC client with imports of the internal implementation of CSI Proxy.
- Update the node PD CSI Driver Windows manifests adding a section like:

```
spec:
  securityContext:
    windowsOptions:
      hostProcess: true
      runAsUserName: "NT AUTHORITY\\Local service"
```

The design doc is in (TODO: link to KEP)
