### ISSUE TITLE
PersistentVolumeClaim by Name {name}: claim in dataSource not bound or invalid

### ISSUE THREAD

**Issue by felipemendes1994** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#1651]
Hello,

I've been trying to clone an existing ReadWriteOnce PVC as ReadOnlyMany one, but without success.

Existing Volume description:
```
Name:          mlp-cache-pvc-20240318
Namespace:     default
StorageClass:  fast
Status:        Bound
Volume:        pvc-6aef82ed-33b1-4527-8367-88d9bcf6c2a6
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: pd.csi.storage.gke.io
               volume.kubernetes.io/storage-provisioner: pd.csi.storage.gke.io
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      100Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Used By:       <none>
Events:        <none>
```

My Volume Clone yml:
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mlp-readonly-cache-pvc-20240327
  # namespace: default ## Commented cause made no difference
spec:
  dataSource:
    name: mlp-cache-pvc-20240318
    kind: PersistentVolumeClaim
  accessModes:
    - ReadOnlyMany
  storageClassName: fast
  resources:
    requests:
      storage: 100Gi
```

When I apply the volume clone yml, It stuck in pending with the following description:
```
Name:          mlp-readonly-cache-pvc-20240327
Namespace:     default
StorageClass:  fast
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: pd.csi.storage.gke.io
               volume.kubernetes.io/storage-provisioner: pd.csi.storage.gke.io
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
DataSource:
  Kind:   PersistentVolumeClaim
  Name:   mlp-cache-pvc-20240318
Used By:  <none>
Events:
  Type     Reason                Age                From                                                                                              Message
  ----     ------                ----               ----                                                                                              -------
  Normal   Provisioning          14s (x7 over 77s)  pd.csi.storage.gke.io_gke-5b7d64186ad785d34b83-17af-79f5-vm_556d6264-d9d7-4ee4-9e50-93f6ff524b04  External provisioner is provisioning volume for claim "default/mlp-readonly-cache-pvc-20240327"
  Warning  ProvisioningFailed    14s (x7 over 77s)  pd.csi.storage.gke.io_gke-5b7d64186ad785d34b83-17af-79f5-vm_556d6264-d9d7-4ee4-9e50-93f6ff524b04  failed to provision volume with StorageClass "fast": error getting handle for DataSource Type PersistentVolumeClaim by Name mlp-cache-pvc-20240318: claim in dataSource not bound or invalid
  Normal   ExternalProvisioning  13s (x7 over 77s)  persistentvolume-controller                                                                       waiting for a volume to be created, either by external provisioner "pd.csi.storage.gke.io" or manually created by system administrator
```

As you can see I got the error `claim in dataSource not bound or invalid`. But my data is valid and created and not attached to any pod.

Currently my cluster runs on 1.27.8-gke.1067004 version.

Any help??
