### ISSUE TITLE
Is ReadWriteMany supported for Hyperdisk?

### ISSUE THREAD

**Issue by tobernguyen** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#1830]
I have looked up and couldn't find any information about CSI supporting `ReadWriteMany` with Hyperdisk Balanced. I tried to create one inside the my GKE cluster and got the error.

```
failed to provision volume with StorageClass "balanced-storage": rpc error: code = Unknown desc = CreateVolume failed to create single zonal disk pvc-70914f74-76b9-4e74-a6d0-936e5525684b: failed to insert zonal disk: unknown Insert disk error: googleapi: Error 400: Invalid value for field 'resource.multiWriter': 'true'. Cannot specify the multi writer field for 'hyperdisk-balanced' disks, please use access mode instead., invalid
```

StorageClass
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: balanced-storage
parameters:
  provisioned-iops-on-create: "160000"
  provisioned-throughput-on-create: 2400Mi
  type: hyperdisk-balanced
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

PVC
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-hyperdisk-balanced-rwx
  namespace: default
spec:
  volumeMode: Block
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  storageClassName: balanced-storage
```

CSI Version: v1.13.6-gke.5

Can someone confirm if `ReadWriteMany` for hyperdisk is not yet supported? Or I'm misconfiguring it.
