### ISSUE TITLE
Admission webhook to label pre-provisioned PDs

### ISSUE THREAD

**Issue by msau42** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#390]
In-tree PDs have an admission [controller](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/storage/persistentvolume/label/admission.go) that queries PD and sets appropriate topology labels + PV.NodeAffinity on manually created PV objects.

Need to decide whether we want to continue to support that with the CSI driver or not.  One limitation of the in-tree controller is I think it already doesn't work with RePD.

**Comment by msau42** [comment]
Need to test in-tree if it's setting PV.NodeAffinity correctly for RePD

**Comment by saad-ali** [comment]
**Background**

The GCE PD in-tree volume plugin adds the following labels on PV creation:

```
  kind: PersistentVolume
  metadata:
    labels:
      failure-domain.beta.kubernetes.io/region: us-central1
      failure-domain.beta.kubernetes.io/zone: us-central1-c
```

The primary purpose of these labels is to ensure that the k8s scheduler takes these constraints in to account during pod scheduling. 

This mechanism is replaced in CSI with a more robust/generic topology mechanism. 
The new mechanism automatically labels nodes when CSI driver starts (see https://github.com/kubernetes/kubernetes/blob/8e8b6a01cf6bf55dea5e2e4f554597a95c82988a/pkg/volume/csi/nodeinfomanager/nodeinfomanager.go#L118).
The new mechanism then fills in the `nodeAffinity` fields in the PV object for provisioned volumes (via external-provisioner):

```
 kind: PersistentVolume
  metadata:
    name: pvc-86512550-981d-498b-8f01-03d67d7b3760
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 9Gi
    csi:
      driver: pd.csi.storage.gke.io
      fsType: ext4
      volumeHandle: ...
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.gke.io/zone
            operator: In
            values:
            - us-central1-a
    persistentVolumeReclaimPolicy: Delete
  status:
    phase: Bound
```

This `nodeAffinity` is then checked by the scheduler (https://github.com/kubernetes/kubernetes/blob/8e8b6a01cf6bf55dea5e2e4f554597a95c82988a/pkg/controller/volume/scheduling/scheduler_binder.go#L590) to ensure the correct behavior (don't schedule to node which does not have access to volume).

**Takeaway**

The main purpose of the [admission controller](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/storage/persistentvolume/label/admission.go) that Michelle mentioned is to ensure that manually provisioned GCE PD in-tree volumes are labeled correctly (because normally the dynamic provisioning process applies the labels).

We could consider creating a similar [Dynamic Admission Control](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/) that fills in the `nodeAffinity` fields if not present for a GCE PD CSI volume. This would be nice to have, but is not a GA blocker for the GCE PD CSI Driver (because this admission controller would be a new component).
