### ISSUE TITLE
Nomad support question

### ISSUE THREAD

**Issue by shankarkc** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#545]
Hi I am trying to use this controller/noe plugin with nomad. Can you please let us know if this supports non kubernetes environment. As of now when I try to port the deployment to K8s I see that node plugin passing some parameters that is specific to K8s.
```
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/pd.csi.storage.gke.io/csi.sock"
```

```
          volumeMounts:
            - name: kubelet-dir
              mountPath: /var/lib/kubelet
              mountPropagation: "Bidirectional"
```
 Can you please let me know how to how this driver can be used with nomad?
