### ISSUE TITLE
Labels of pv are missing

### ISSUE THREAD

**Issue by hua82556281** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#797]
with k8s version 1.17.16, when i use gce-pd to provison pv by storageclass, there are two labels `failure-domain.beta.kubernetes.io/region, failure-domain.beta.kubernetes.io/zone` in pv, you can see it as below
```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: gce-pd-dynamic-provisioner
    velero.io/alibabacloud-restore-plugin: "1"
  creationTimestamp: "2021-06-07T07:04:23Z"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    failure-domain.beta.kubernetes.io/region: europe-west1
    failure-domain.beta.kubernetes.io/zone: europe-west1-b
  name: pvc-165b7c53-1263-4469-a36f-84994da94a3b
  resourceVersion: "29425366"
  selfLink: /api/v1/persistentvolumes/pvc-165b7c53-1263-4469-a36f-84994da94a3b
  uid: c5fae559-1ba0-43c1-b864-4d44b76ae1b2
```
however, when i switch to pd.csi.storage.gke.io the labels are missing, as below
```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: pd.csi.storage.gke.io
  creationTimestamp: "2021-07-01T07:33:42Z"
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/pd-csi-storage-gke-io
...
```

in k8s version 1.18.18, both gce-pd and pd.csi.storage.gke.io are missing labels. I am not sure whether it is related with migaration feature result in pv always provisioned by pd.csi.storage.gke.io even if i used gce-pd.
`kubectl get csinodes -o yaml`
```
apiVersion: v1
items:
- apiVersion: storage.k8s.io/v1
  kind: CSINode
  metadata:
    annotations:
      storage.alpha.kubernetes.io/migrated-plugins: kubernetes.io/gce-pd
    creationTimestamp: "2021-07-02T06:27:58Z"
    managedFields:

```

so please help me to figure out why is it and how to get labels `failure-domain.beta.kubernetes.io/region, failure-domain.beta.kubernetes.io/zone` automatically by pd.csi.storage.gke.io?

**Comment by mattcary** [comment]
Those are the beta topology labels. They have been replaced by the topology.kubernetes.io labels, see https://kubernetes.io/docs/reference/labels-annotations-taints/#topologykubernetesiozone for more details.

**Comment by mattcary** [comment]
Sorry, I got that wrong, this driver adds the topology.gke.io/zone key, see https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/#topology.

**Comment by hua82556281** [comment]
hi, thank you for your response. But i think this topology key affects `nodeAffinity` as below, it not located under `labels`. 
```
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.gke.io/zone
          operator: In
          values:
          - europe-west1-d
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gcp-test
  volumeMode: Filesystem
status:
  phase: Bound
```
should be like this, because velero only recogonize zone information under `labels`. 
![image](https://user-images.githubusercontent.com/80674375/124385638-31825000-dd09-11eb-8c75-e06f88bd175b.png)

**Comment by hua82556281** [comment]
i want to know how does this driver adds the topology.gke.io/zone under `labels`

**Comment by AlwaySummit** [comment]
Hi guys, I'm facing the same error which causes the failure of velero backup. As you can see the source code of velero, it looks for the specific label to get zone information.
```
const (
	zoneLabelDeprecated = "failure-domain.beta.kubernetes.io/zone"
	zoneLabel           = "topology.kubernetes.io/zone"
)
pvFailureDomainZone, labelFound := pv.Labels[zoneLabel]
if !labelFound {
   log.Infof("label %q is not present on PersistentVolume, checking deprecated label...", zoneLabel)
   pvFailureDomainZone, labelFound = pv.Labels[zoneLabelDeprecated]
   if !labelFound {
      log.Infof("label %q is not present on PersistentVolume", zoneLabelDeprecated)
   }
}
```
If the labels are not found, the value of pvFailureDomainZone is null which results in the error when calling GetVolumeInfo.
```
volumeType, iops, err := volumeSnapshotter.GetVolumeInfo(volumeID, pvFailureDomainZone)
if err != nil {
   return errors.WithMessage(err, "error getting volume info")
}
```
```
time="2021-06-22T12:01:03Z" level=error msg="Error backing up item" backup=default/velero-backup-metering-20210622120057 error="error getting volume info: rpc error: code = Unknown desc = googleapi: Error 400: Invalid value for field 'zone': ''. Must be a match of regex '[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?', invalid" logSource="pkg/backup/backup.go:431" name=metering-log-metering-0
```
Any insights or suggestions to make it work again?
BTW, it worked in k8s version 1.17 because I was using in-tree plugin.

**Comment by msau42** [comment]
I think the issue pointed out here is that the topology labels are put on the PV.Spec.NodeAffinity field, but not in PV.Metadata.Labels like it did for the the in-tree driver.

**Comment by AlwaySummit** [comment]
Hi @msau42 

Thanks for your response. That's correct but these two kinds of labels are a little bit different from each other. As you can see, the label in NodeAffinity is `topology.gke.io/zone`. But the expected label in Metadata is kind of like `failure-domain.beta.kubernetes.io/zone` or `topology.kubernetes.io/zone`.
```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: pd.csi.storage.gke.io
  creationTimestamp: "2021-07-01T04:34:47Z"
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/pd-csi-storage-gke-io
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.gke.io/zone
          operator: In
          values:
          - europe-west1-c
  persistentVolumeReclaimPolicy: Delete
  storageClassName: hc-default
  volumeMode: Filesystem
status:
  phase: Bound
```
BTW, I notice that there is a logic in csi-translation-lib which is mainly responsible for replacing the CSI topology to Kubernetes Zone topology label and adding Kubernetes Topology labels(zone) if they do not exist. As far as I can see, neither of them is properly done when creating volume. So is there any possibility that the function is never called during the PV creation?
```
// translateTopologyFromCSIToInTree translate a CSI topology to
// Kubernetes topology and add topology labels to it. Note that this function
// will only work for plugin with a single topologyKey that translates to
// Kubernetes zone(and region if regionParser is passed in).
// If a plugin has more than one topologyKey, it will need to be processed
// separately by the plugin.
// If regionParser is nil, no region NodeAffinity will be added. If not nil,
// it'll be passed to regionTopologyHandler, which will add region topology NodeAffinity
// and labels for the given PV. It assumes the Zone NodeAffinity already exists.
// In short this function will,
// 1. Replace all CSI topology to Kubernetes Zone topology label
// 2. Process and generate region topology if a regionParser is passed
// 3. Add Kubernetes Topology labels(zone) if they do not exist
func translateTopologyFromCSIToInTree(pv *v1.PersistentVolume, csiTopologyKey string, regionParser regionParserFn) error {

	zoneLabel, _ := getTopologyLabel(pv)

	// 1. Replace all CSI topology to Kubernetes Zone label
	err := replaceTopology(pv, csiTopologyKey, zoneLabel)
	if err != nil {
		return fmt.Errorf("Failed to replace CSI topology to Kubernetes topology, error: %v", err)
	}

	// 2. Take care of region topology if a regionParser is passed
	if regionParser != nil {
		// let's make less strict on this one. Even if there is an error in the region processing, just ignore it
		err = regionTopologyHandler(pv, regionParser)
		if err != nil {
			return fmt.Errorf("Failed to handle region topology. error: %v", err)
		}
	}

	// 3. Add labels about Kubernetes Topology
	zoneVals := getTopologyValues(pv, zoneLabel)
	if len(zoneVals) > 0 {
		if pv.Labels == nil {
			pv.Labels = make(map[string]string)
		}
		_, zoneOK := pv.Labels[zoneLabel]
		if !zoneOK {
			zoneValStr := strings.Join(zoneVals, labelMultiZoneDelimiter)
			pv.Labels[zoneLabel] = zoneValStr
		}
	}

	return nil
}
```

**Comment by AlwaySummit** [comment]
Besides, this is a PV which is created by in tree plugin. No matter the label in metadata or nodeAffinity, they are all the kubernetes label other than `topology.gke.io/zone` which belongs to CSI driver.
```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: gce-pd-dynamic-provisioner
    velero.io/alibabacloud-restore-plugin: "1"
  creationTimestamp: "2021-06-07T07:04:23Z"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    failure-domain.beta.kubernetes.io/region: europe-west1
    failure-domain.beta.kubernetes.io/zone: europe-west1-b
  name: pvc-165b7c53-1263-4469-a36f-84994da94a3b
  resourceVersion: "29425366"
  selfLink: /api/v1/persistentvolumes/pvc-165b7c53-1263-4469-a36f-84994da94a3b
  uid: c5fae559-1ba0-43c1-b864-4d44b76ae1b2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: alertmanager-alertmanager-db-alertmanager-alertmanager-0
    namespace: monitoring
    resourceVersion: "29425364"
    uid: 4c557b99-9f60-4fc0-a2e7-21d1b9923d09
  gcePersistentDisk:
    fsType: xfs
    pdName: restore-c2f0fef5-5f4b-43aa-9daa-be8b5faa46bc
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: failure-domain.beta.kubernetes.io/zone
          operator: In
          values:
          - europe-west1-b
        - key: failure-domain.beta.kubernetes.io/region
          operator: In
          values:
          - europe-west1
  persistentVolumeReclaimPolicy: Delete
  storageClassName: hc-default
  volumeMode: Filesystem
status:
  phase: Bound
```

**Comment by msau42** [comment]
Sorry I'm trying to get the scenario straight as both intree and csi drivers are mentioned. Can you clarify:
1) Is your storageclass using the intree or csi provisioner?
2) Is CSI migration for gce enabled in your cluster?

**Comment by hua82556281** [comment]
1. Both intree and csi I used in storageclass. With k8s version 1.17.16, when i use gce-pd to provison pv by storageclass, there are two labels `failure-domain.beta.kubernetes.io/region, failure-domain.beta.kubernetes.io/zone` in pv. But there is not when use csi.
With k8s version 1.18.18, both of intree and csi all missing labels.
2. disabled In 1.17.16 k8s version. and enabled in 1.18.18 k8s version.

**Comment by msau42** [comment]
What version of the csi driver and csi-provisioner sidecar are you using? We need to check the version of csi-translation-lib that you are using.

**Comment by hua82556281** [comment]
Hi, actually I am not sure how to check their version. I used the source code `gcp-compute-persistent-disk-csi-driver` to install csi driver, I list the `image.yaml` in `stable-master` to below.
```
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-provisioner
imageTag:
  name: k8s.gcr.io/sig-storage/csi-provisioner
  newTag: "v2.2.1"

---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-attacher
imageTag:
  name: k8s.gcr.io/sig-storage/csi-attacher
  newTag: "v3.2.1"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-resizer
imageTag:
  name: k8s.gcr.io/sig-storage/csi-resizer
  newTag: "v1.2.0"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-snapshotter
imageTag:
  name: k8s.gcr.io/sig-storage/csi-snapshotter
  newTag: "v3.0.3"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-node-registrar
imageTag:
  name: k8s.gcr.io/sig-storage/csi-node-driver-registrar
  newTag: "v2.1.0"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-gcepd-driver
imageTag:
  name: gke.gcr.io/gcp-compute-persistent-disk-csi-driver
  # Don't change stable image without changing pdImagePlaceholder in
  # test/k8s-integration/main.go
  newTag: "v1.2.1-gke.0"
---

```
