### ISSUE TITLE
Can't use ReadOnlyMany volume restored from Snapshot with controller-publish-readonly provisioner option

### ISSUE THREAD

**Issue by tsmetana** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#872]
When using the new [`controller-publish-readonly` command-line option](https://github.com/kubernetes-csi/external-provisioner/pull/469) in the external provisioner sidecar, the ReadOnlyMany volumes seem to be still attempted to be mounted read-write. Moreover it looks like when the ROX volume is restored from snapshot, the kubelet still attempts to even create a filesystem on it.

Reproducer:
1. Create a CSI volume:
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-csi
  resources:
    requests:
      storage: 1Gi
```
2. Start a pod that writes some data on it (optionally, just to have something for verification).
3. Create a snapshot of the volume:
```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: mysnap-1
spec:
  volumeSnapshotClassName: csi-gce-pd-vsc
  source:
    persistentVolumeClaimName: myclaim1
```
4. Restore the snapshot to ReadOnlyMany volume
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1-restore
spec:
  accessModes:
  - ReadOnlyMany
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: mysnap-1
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard-csi
```
5. Try to use the restored volume in a pod:
```
kind: Pod
apiVersion: v1
metadata:
  name: pod-restore
  labels:
    name: pod-restore
spec:
  containers:
    - name: busybox
      image: gcr.io/google_containers/busybox
      command:
        - "/bin/sh"
        - "-c"
        - "while true; do sleep 1; done"
      volumeMounts:
      - mountPath: "/mnt/test"
        name: vol
        readOnly: true
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: pvc1-restore
        readOnly: true
```

Result:
Pod fails to start with message similar to this one in the log:
```
Warning  FailedMount             16s (x7 over 51s)  kubelet                  MountVolume.MountDevice failed for volume "pvc-e4269d3a-3a2d-4920-8917-a30c0a0773e7" : rpc error: code = Internal desc = Failed to format and mount device from ("/dev/disk/by-id/google-pvc-e4269d3a-3a2d-4920-8917-a30c0a0773e7") to ("/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-e4269d3a-3a2d-4920-8917-a30c0a0773e7/globalmount") with fstype ("ext4") and options ([]): format of disk "/dev/disk/by-id/google-pvc-e4269d3a-3a2d-4920-8917-a30c0a0773e7" failed: type:("ext4") target:("/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-e4269d3a-3a2d-4920-8917-a30c0a0773e7/globalmount") options:("defaults") errcode:(exit status 1) output:(mke2fs 1.45.6 (20-Mar-2020)
/dev/disk/by-id/google-pvc-e4269d3a-3a2d-4920-8917-a30c0a0773e7: Read-only file system while setting up superblock
```

This looks to be incorrect: the volume should not be attempted to be mounted read-write and the attempt to create a filesystem on a formatted drive pre-populated with data looks quite dangerous. I will try to tinker with this but if someone reading this had an idea, I'm interested. I'm also not sure who exactly is at fault here: might be also kubelet.
